temId(rondônia, 11).
temId(acre, 12).
temId(amazonas, 13).
temId(roraima, 14).
temId(pará, 15).
temId(amapá, 16).
temId(tocantins, 17).
temId(maranhão, 21).
temId(piauí, 22).
temId(ceará, 23).
temId(rio_grande_do_norte, 24).
temId(paraíba, 25).
temId(pernambuco, 26).
temId(alagoas, 27).
temId(sergipe, 28).
temId(bahia, 29).
temId(minas_gerais, 31).
temId(espírito_santo, 32).
temId(rio_de_janeiro, 33).
temId(são_paulo, 35).
temId(paraná, 41).
temId(santa_catarina, 42).
temId(rio_grande_do_sul, 43).
temId(mato_grosso_do_sul, 50).
temId(mato_grosso, 51).
temId(goiás, 52).
temId(distrito_federal, 53).
