state_to_uf = {
    'Rondônia': 'ro',
    'Acre': 'ac',
    'Amazonas': 'am',
    'Roraima': 'rr',
    'Pará': 'pa',
    'Amapá': 'ap',
    'Tocantins': 'to',
    'Maranhão': 'ma',
    'Piauí': 'pi',
    'Ceará': 'ce',
    'Rio Grande do Norte': 'rn',
    'Paraíba': 'pb',
    'Pernambuco': 'pe',
    'Alagoas': 'al',
    'Sergipe': 'se',
    'Bahia': 'ba',
    'Minas Gerais': 'mg',
    'Espírito Santo': 'es',
    'Rio de Janeiro': 'rj',
    'São Paulo': 'sp',
    'Paraná': 'pr',
    'Santa Catarina': 'sc',
    'Rio Grande do Sul': 'rs',
    'Mato Grosso do Sul': 'ms',
    'Mato Grosso': 'mt',
    'Goiás': 'go',
    'Distrito Federal': 'df'
}
